apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "weather.fullname" . }}-config
  labels:
    app: {{ include "weather.name" . }}
data:
{{- range $k, $v := .Values.config }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
