{{- if not .Values.externalSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "weather.fullname" . }}-secrets
  labels:
    app: {{ include "weather.name" . }}
type: Opaque
stringData:
  OPENWEATHER_API_KEY: {{ .Values.secrets.OPENWEATHER_API_KEY | quote }}
{{- end }}
