apiVersion: v1
kind: ConfigMap
metadata:
  name: weather-config
  namespace: weather
data:
  LOG_LEVEL: INFO
  CACHE_TTL_SECONDS: "300"
  MAX_STALE_SECONDS: "1800"
  HTTP_TIMEOUT_SECONDS: "2.0"
  RATE_LIMIT: "50/60"
