apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: weather-api
  namespace: weather
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
  - hosts:
    - api.weather.example.com
    secretName: weather-api-tls
  rules:
  - host: api.weather.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: weather-api
            port:
              number: 80
