apiVersion: v1
kind: Service
metadata:
  name: weather-api
  namespace: weather
spec:
  type: ClusterIP
  selector:
    app: weather-api
  ports:
    - name: http
      port: 80
      targetPort: 8000
